/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as HistoricoFraudeRouteImport } from './routes/historico-fraude'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ColaRouteImport } from './routes/cola'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestingIndexRouteImport } from './routes/testing.index'
import { Route as TestingRunIdRouteImport } from './routes/testing.$runId'
import { Route as AlertaIdRouteImport } from './routes/alerta.$id'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoFraudeRoute = HistoricoFraudeRouteImport.update({
  id: '/historico-fraude',
  path: '/historico-fraude',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaRoute = ColaRouteImport.update({
  id: '/cola',
  path: '/cola',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingIndexRoute = TestingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestingRoute,
} as any)
const TestingRunIdRoute = TestingRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => TestingRoute,
} as any)
const AlertaIdRoute = AlertaIdRouteImport.update({
  id: '/alerta/$id',
  path: '/alerta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cola': typeof ColaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/historico-fraude': typeof HistoricoFraudeRoute
  '/modelos': typeof ModelosRoute
  '/monitor': typeof MonitorRoute
  '/testing': typeof TestingRouteWithChildren
  '/alerta/$id': typeof AlertaIdRoute
  '/testing/$runId': typeof TestingRunIdRoute
  '/testing/': typeof TestingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cola': typeof ColaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/historico-fraude': typeof HistoricoFraudeRoute
  '/modelos': typeof ModelosRoute
  '/monitor': typeof MonitorRoute
  '/alerta/$id': typeof AlertaIdRoute
  '/testing/$runId': typeof TestingRunIdRoute
  '/testing': typeof TestingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cola': typeof ColaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/historico-fraude': typeof HistoricoFraudeRoute
  '/modelos': typeof ModelosRoute
  '/monitor': typeof MonitorRoute
  '/testing': typeof TestingRouteWithChildren
  '/alerta/$id': typeof AlertaIdRoute
  '/testing/$runId': typeof TestingRunIdRoute
  '/testing/': typeof TestingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/cola'
    | '/configuracion'
    | '/dashboard'
    | '/historico-fraude'
    | '/modelos'
    | '/monitor'
    | '/testing'
    | '/alerta/$id'
    | '/testing/$runId'
    | '/testing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/cola'
    | '/configuracion'
    | '/dashboard'
    | '/historico-fraude'
    | '/modelos'
    | '/monitor'
    | '/alerta/$id'
    | '/testing/$runId'
    | '/testing'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/cola'
    | '/configuracion'
    | '/dashboard'
    | '/historico-fraude'
    | '/modelos'
    | '/monitor'
    | '/testing'
    | '/alerta/$id'
    | '/testing/$runId'
    | '/testing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ColaRoute: typeof ColaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  HistoricoFraudeRoute: typeof HistoricoFraudeRoute
  ModelosRoute: typeof ModelosRoute
  MonitorRoute: typeof MonitorRoute
  TestingRoute: typeof TestingRouteWithChildren
  AlertaIdRoute: typeof AlertaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-fraude': {
      id: '/historico-fraude'
      path: '/historico-fraude'
      fullPath: '/historico-fraude'
      preLoaderRoute: typeof HistoricoFraudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cola': {
      id: '/cola'
      path: '/cola'
      fullPath: '/cola'
      preLoaderRoute: typeof ColaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/': {
      id: '/testing/'
      path: '/'
      fullPath: '/testing/'
      preLoaderRoute: typeof TestingIndexRouteImport
      parentRoute: typeof TestingRoute
    }
    '/testing/$runId': {
      id: '/testing/$runId'
      path: '/$runId'
      fullPath: '/testing/$runId'
      preLoaderRoute: typeof TestingRunIdRouteImport
      parentRoute: typeof TestingRoute
    }
    '/alerta/$id': {
      id: '/alerta/$id'
      path: '/alerta/$id'
      fullPath: '/alerta/$id'
      preLoaderRoute: typeof AlertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TestingRouteChildren {
  TestingRunIdRoute: typeof TestingRunIdRoute
  TestingIndexRoute: typeof TestingIndexRoute
}

const TestingRouteChildren: TestingRouteChildren = {
  TestingRunIdRoute: TestingRunIdRoute,
  TestingIndexRoute: TestingIndexRoute,
}

const TestingRouteWithChildren =
  TestingRoute._addFileChildren(TestingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  ColaRoute: ColaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  HistoricoFraudeRoute: HistoricoFraudeRoute,
  ModelosRoute: ModelosRoute,
  MonitorRoute: MonitorRoute,
  TestingRoute: TestingRouteWithChildren,
  AlertaIdRoute: AlertaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
